// Generated by tools/hns-layout/generate_hns_live_battle_layout.py; do not edit.
package com.dualdex.pokemon.hns

object HnsDoublesLayout {
    val UNSUPPRESSIBLE_ABILITIES = setOf(121, 161, 176, 197, 208, 209, 210, 211, 213, 225, 241, 248, 266, 267, 278, 279, 307)
}
