package com.dualdex.pokemon.hns

// Generated by tools/hns-field-status/generate_hns_field_status.py from the pinned
// include/constants/battle.h and the reviewed tools/hns-field-status/field_audit.json
// (pokehns-expansion 1f42b74dff0e9fe942419845d040663dd829a973). Do not edit.

/** One pinned `gFieldStatuses` bit, in bit order (`include/constants/battle.h`). */
enum class HnsFieldStatus(val bit: Int, val sourceSymbol: String, val displayName: String) {
    MAGIC_ROOM(0, "STATUS_FIELD_MAGIC_ROOM", "Magic Room"),
    TRICK_ROOM(1, "STATUS_FIELD_TRICK_ROOM", "Trick Room"),
    WONDER_ROOM(2, "STATUS_FIELD_WONDER_ROOM", "Wonder Room"),
    MUD_SPORT(3, "STATUS_FIELD_MUDSPORT", "Mud Sport"),
    WATER_SPORT(4, "STATUS_FIELD_WATERSPORT", "Water Sport"),
    GRAVITY(5, "STATUS_FIELD_GRAVITY", "Gravity"),
    GRASSY_TERRAIN(6, "STATUS_FIELD_GRASSY_TERRAIN", "Grassy Terrain"),
    MISTY_TERRAIN(7, "STATUS_FIELD_MISTY_TERRAIN", "Misty Terrain"),
    ELECTRIC_TERRAIN(8, "STATUS_FIELD_ELECTRIC_TERRAIN", "Electric Terrain"),
    PSYCHIC_TERRAIN(9, "STATUS_FIELD_PSYCHIC_TERRAIN", "Psychic Terrain"),
    ION_DELUGE(10, "STATUS_FIELD_ION_DELUGE", "Ion Deluge"),
    FAIRY_LOCK(11, "STATUS_FIELD_FAIRY_LOCK", "Fairy Lock");

    /** The pinned single-bit mask. */
    val mask: Int get() = 1 shl bit
}

internal object HnsFieldStatusData {
    const val PINNED_COMMIT: String = "1f42b74dff0e9fe942419845d040663dd829a973"

    const val STATUS_FIELD_MAGIC_ROOM: Int = 0x00000001
    const val STATUS_FIELD_TRICK_ROOM: Int = 0x00000002
    const val STATUS_FIELD_WONDER_ROOM: Int = 0x00000004
    const val STATUS_FIELD_MUDSPORT: Int = 0x00000008
    const val STATUS_FIELD_WATERSPORT: Int = 0x00000010
    const val STATUS_FIELD_GRAVITY: Int = 0x00000020
    const val STATUS_FIELD_GRASSY_TERRAIN: Int = 0x00000040
    const val STATUS_FIELD_MISTY_TERRAIN: Int = 0x00000080
    const val STATUS_FIELD_ELECTRIC_TERRAIN: Int = 0x00000100
    const val STATUS_FIELD_PSYCHIC_TERRAIN: Int = 0x00000200
    const val STATUS_FIELD_ION_DELUGE: Int = 0x00000400
    const val STATUS_FIELD_FAIRY_LOCK: Int = 0x00000800
    const val STATUS_FIELD_TERRAIN_ANY: Int = 0x000003C0 // STATUS_FIELD_GRASSY_TERRAIN | STATUS_FIELD_MISTY_TERRAIN | STATUS_FIELD_ELECTRIC_TERRAIN | STATUS_FIELD_PSYCHIC_TERRAIN

    /** Union of every reviewed pinned bit; any other bit is unknown and fails closed. */
    const val KNOWN_MASK: Int = 0x00000FFF

    const val ABILITY_ANALYTIC: Int = 148
    const val ABILITY_GALE_WINGS: Int = 177
    const val ABILITY_GRASS_PELT: Int = 179
    const val ABILITY_HADRON_ENGINE: Int = 289
    const val ABILITY_QUARK_DRIVE: Int = 282

    /** Ordinary moves whose pinned `gravityBanned` is not FALSE (Gravity makes them fail). */
    val gravityBannedOrdinaryMoveIds: Set<Int> = setOf(678)

    /** Ordinary moves whose pinned priority is positive, not a provable literal <= 0, or a Triage healing move. */
    val positivePriorityOrdinaryMoveIds: Set<Int> = setOf(98, 183, 245, 364, 410, 418, 420, 425, 453, 663, 785)

    /** Every reviewed request-local field rule name (implemented by HnsFieldContextPolicy). */
    val contextRuleNames: Set<String> = setOf(
        "magic_room_held_items_neutral",
        "trick_room_attacker_not_analytic",
        "trick_room_attacker_analytic",
        "wonder_room_swaps_defensive_stat",
        "mud_sport_non_electric_move",
        "mud_sport_electric_move",
        "water_sport_non_fire_move",
        "water_sport_fire_move",
        "gravity_non_ground_unbanned_move",
        "gravity_ground_move",
        "gravity_banned_move",
        "grassy_terrain_non_grass_move",
        "grassy_terrain_grass_move",
        "grassy_terrain_grass_pelt_defender",
        "grassy_terrain_attacker_analytic",
        "misty_terrain_non_dragon_move",
        "misty_terrain_dragon_move",
        "electric_terrain_non_electric_move",
        "electric_terrain_electric_move",
        "electric_terrain_paradox_ability",
        "electric_terrain_attacker_analytic",
        "psychic_terrain_non_psychic_non_priority_move",
        "psychic_terrain_psychic_move",
        "psychic_terrain_priority_move",
        "ion_deluge_non_normal_move",
        "ion_deluge_normal_move",
        "fairy_lock_escape_only",
        "unknown_field_bits",
    )
}
