// Generated by tools/hns-layout/generate_hns_live_battle_layout.py; do not edit.
// Pinned source: 1f42b74dff0e9fe942419845d040663dd829a973
package com.dualdex.pokemon.hns

object HnsGroupDLayout {
    const val NUM_STATS = 6
    const val GIMMICKS_COUNT = 6
    const val GIMMICK_DYNAMAX = 4
    const val METRONOME_ITEM_COUNTER_MAX = 255
    const val METRONOME_ITEM_COUNTER_WIDTH = 8
    const val TRANSFORMED_MON_SPECIES_WIDTH = 11
    const val SPECIES_COUNT = 1573
    const val SLOW_START_MAX = 7
    const val FIRST_TURN_MAX = 3
    const val STATE_NONE = 0
    const val STATE_UNDERGROUND = 1
    const val STATE_UNDERWATER = 2
    const val STATE_ON_AIR = 3
    const val STATE_PHANTOM_FORCE = 4
    const val STATE_SKY_DROP = 5
    const val STATE_COMMANDER = 6
    const val SEMI_INVULNERABLE_COUNT = 7
}
