// Generated by tools/hns-layout/generate_hns_live_battle_layout.py; do not edit.
// Pinned source: 1f42b74dff0e9fe942419845d040663dd829a973
package com.dualdex.pokemon.hns

object HnsGroupDLayout {
    const val NUM_STATS = 6
    const val GIMMICKS_COUNT = 6
    const val GIMMICK_DYNAMAX = 4
    const val SLOW_START_MAX = 7
    const val FIRST_TURN_MAX = 3
}
