#!/usr/bin/env python3
"""Reconcile reviewed Group E dispositions with BOTH generated inventories; never infer tiers."""
import argparse
import csv
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
HERE = pathlib.Path(__file__).resolve().parent
PIN = '1f42b74dff0e9fe942419845d040663dd829a973'
REMAINDER = {'UNSUPPORTED_DAMAGE_RELEVANT', 'UNCLASSIFIED'}


def rows(path):
    return list(csv.DictReader(path.open(), delimiter='\t'))


def render(doc, abilities, items, item_decisions):
    if doc['pinned_commit'] != PIN:
        raise ValueError('Group E source pin changed')
    expected = {a['id'] for a in abilities if a['proposed_category'] in REMAINDER} | {'277', '280'}
    if set(doc['abilities']) != expected:
        raise ValueError('Group E ability assignment domain differs from inventory remainder + exact Charge handoff')
    families = {k for k, v in item_decisions['families'].items() if v['category'] in REMAINDER}
    exceptions = {k for k, v in item_decisions['identity_exceptions'].items() if v['category'] in REMAINDER}
    if set(doc['item_families']) != families or set(doc['item_identities']) != exceptions:
        raise ValueError('Group E item assignments must equal unsupported/unclassified families and exceptions')
    for group in doc['groups'].values():
        if group['tier'] not in ('EXACT', 'CAVEATED_ESTIMATE', 'HARD_REFUSAL'):
            raise ValueError('invalid Group E tier')
        for key in ('reason', 'state', 'tests'):
            if not group.get(key):
                raise ValueError('Group E assignment missing ' + key)
    entries = []
    for a in abilities:
        if a['id'] in doc['abilities']:
            entries.append(('ability', a['id'], a['symbol'], a['display_name'],
                            doc['abilities'][a['id']], a['proposed_category'], ', '.join([a['evidence']] + doc.get('ability_sources', {}).get(a['id'], []))))
    for i in items:
        if i['category'] not in REMAINDER:
            continue
        group = doc['item_identities'].get(i['symbol'], doc['item_families'].get(i['hold_effect']))
        if group is None:
            raise ValueError('Unassigned Group E identity: ' + i['symbol'])
        refs = item_decisions['families'][i['hold_effect']]['reviewed_refs']
        if i['symbol'] in doc['item_identities']:
            refs = doc['identity_sources'][i['symbol']]
        entries.append(('item', i['id'], i['symbol'], i['display_name'], group, i['category'], ', '.join(refs)))
    kt = ['package com.dualdex.pokemon.hns', '',
          '// Generated by tools/hns-group-e/generate_closure.py. Do not edit.',
          'object HnsGroupEData {']
    for kind in ('ability', 'item'):
        kt.append(f'    val {kind}Dispositions: Map<Int, HnsGroupEDisposition> = mapOf(')
        for k, ident, symbol, name, family, category, refs in entries:
            if k != kind:
                continue
            g = doc['groups'][family]
            quote = lambda s: json.dumps(s, ensure_ascii=False).replace('$', '\\$')
            kt.append(f'        {ident} to HnsGroupEDisposition(HnsGroupETier.{g["tier"]}, {quote(family)}, {quote(g["reason"])}, {quote(refs)}),')
        kt.append('    )')
    kt.extend(['}', ''])
    md = ['# Group E generated identity matrix', '',
          f'Pinned source: `{PIN}`. Generated from `tools/hns-group-e/decisions.json` and the ability/item audits.', '',
          'The tier is the reviewed disposition of the unresolved consequence. Existing exact and request-local irrelevant proofs take precedence. CAVEATED_ESTIMATE requires an existing positive RELEVANT proof; UNKNOWN never becomes an estimate. Each refusal names the side and identity followed by the reason below. The detailed production decision retains its narrower missing-operand rationale.', '',
          'EXACT Charge entries require authoritative live operands. Independent format, move, identity, field and item gates always remain active.', '',
          '| Kind / ID | Symbol / display name | Family | Audit blocker | Tier | Required state / observation | Production reason | Pinned source | Tests |',
          '|---|---|---|---|---|---|---|---|---|']
    for kind, ident, symbol, name, family, category, refs in entries:
        g = doc['groups'][family]
        fields = [f'{kind} {ident}', f'`{symbol}` / {name}', family, category, g['tier'], g['state'], g['reason'], refs, g['tests']]
        md.append('| ' + ' | '.join(x.replace('|', '\\|').replace('\n', ' ') for x in fields) + ' |')
    return '\n'.join(kt), '\n'.join(md) + '\n'


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    p.add_argument('--upstream-dir')
    args = p.parse_args()
    doc = json.loads((HERE / 'decisions.json').read_text())
    if args.upstream_dir:
        upstream = pathlib.Path(args.upstream_dir)
        if subprocess.check_output(['git', '-C', str(upstream), 'rev-parse', 'HEAD'], text=True).strip() != PIN:
            raise ValueError('wrong upstream revision')
        for e in doc['source_checks']:
            path, line = e['source'].rsplit(':', 1)
            if e['contains'] not in (upstream / path).read_text().splitlines()[int(line)-1]:
                raise ValueError('Group E source assertion changed: ' + e['source'])
    kt, md = render(doc, rows(ROOT / 'tools/hns-abilities/ability_inventory.tsv'),
                    rows(ROOT / 'tools/hns-items/item_inventory.tsv'),
                    json.loads((ROOT / 'tools/hns-items/decisions.json').read_text()))
    for path, output in [(ROOT / 'app/src/main/java/com/dualdex/pokemon/hns/HnsGroupEData.kt', kt),
                         (ROOT / 'docs/HNS_GROUP_E_MATRIX.md', md)]:
        if args.check:
            if path.read_text() != output:
                raise ValueError('stale generated Group E artifact: ' + str(path))
        else:
            path.write_text(output)
    print('Group E: complete ability/item remainder reconciled; generated production data and matrix match')


if __name__ == '__main__':
    main()
