/*
 * H&S 2.0.5 differential damage test (issue #90).
 *
 * Reads the committed, ROM-free golden corpus generated by tools/hns-damage-oracle from the pinned
 * H&S battle engine, turns every scenario into the H&S calculation request DualDex production
 * builds (the shape of DamageCalculator.kt buildCalcRequestJson), executes it with the shipped
 * QuickJS engine and bundle, and compares the complete 16-roll vector exactly. There is no
 * tolerance: H&S damage is integer arithmetic.
 *
 *   ./native/build/test_hns_damage_oracle [corpus.json] [known_divergences.json]
 *
 * Every mismatch is printed as one machine-readable line
 *   HNS_ORACLE_MISMATCH {"scenario":...,"surface":...,"firstDifferingRoll":k,"expected":[...],
 *                        "actual":[...],"request":{...}}
 * and fails the run, unless the scenario is listed in tools/hns-damage-oracle/known_divergences.json
 * with its current calculator vector pinned. Any different wrong vector fails too. A registered
 * scenario that now matches the oracle fails, so a fix cannot leave a stale register behind.
 *
 * The expected values come only from the corpus; this file contains no damage arithmetic.
 */
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "js_calc_engine.h"
#include "json_lite.h"

#define ROLL_COUNT 16
#define HNS_PINNED_COMMIT "1f42b74dff0e9fe942419845d040663dd829a973"
#define ORACLE_SCHEMA_VERSION 1
#define MAX_DIVERGENCES 512

static int g_failures = 0;
static int g_self_checks = 0;

static void fail(const char* fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "FAIL: ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    g_failures++;
}

static void self_check(const char* what, int condition) {
    g_self_checks++;
    if (!condition) fail("self-test: %s", what);
}

static char* read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long n = ftell(f);
    if (n < 0 || fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t got = fread(buf, 1, (size_t)n, f);
    fclose(f);
    if (got != (size_t)n) { free(buf); return NULL; }
    buf[n] = '\0';
    return buf;
}

/* ---------------------------------------------------------------- string builder */

typedef struct {
    char* data;
    size_t len;
    size_t cap;
    int oom;
} sbuf;

static void sb_append(sbuf* sb, const char* fmt, ...) {
    if (sb->oom) return;
    for (;;) {
        va_list ap;
        va_start(ap, fmt);
        size_t room = sb->cap - sb->len;
        int n = vsnprintf(sb->data ? sb->data + sb->len : NULL, sb->data ? room : 0, fmt, ap);
        va_end(ap);
        if (n < 0) { sb->oom = 1; return; }
        if (sb->data && (size_t)n < room) { sb->len += (size_t)n; return; }
        size_t want = (sb->cap ? sb->cap * 2 : 1024) + (size_t)n + 1;
        char* grown = (char*)realloc(sb->data, want);
        if (!grown) { sb->oom = 1; return; }
        sb->data = grown;
        sb->cap = want;
    }
}

static void sb_json_string(sbuf* sb, const char* s) {
    sb_append(sb, "\"");
    for (const char* p = s; *p; p++) {
        if (*p == '"' || *p == '\\') sb_append(sb, "\\%c", *p);
        else if ((unsigned char)*p < 0x20) sb_append(sb, "\\u%04x", (unsigned char)*p);
        else sb_append(sb, "%c", *p);
    }
    sb_append(sb, "\"");
}

/* ---------------------------------------------------------------- strict field access */

typedef struct {
    char message[512];
} err_t;

static int set_err(err_t* err, const char* fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(err->message, sizeof(err->message), fmt, ap);
    va_end(ap);
    return 0;
}

static int is_obj(const jl_value* v) { return v && v->type == JL_OBJ; }

static int get_int(const jl_value* obj, const char* key, long lo, long hi, long* out, err_t* err) {
    const jl_value* v = jl_get(obj, key);
    if (!jl_is_num(v)) return set_err(err, "field %s missing or not a number", key);
    double d = jl_num(v);
    if (d != (double)(long)d) return set_err(err, "field %s is not integral", key);
    if ((long)d < lo || (long)d > hi) return set_err(err, "field %s=%ld out of range", key, (long)d);
    *out = (long)d;
    return 1;
}

static int get_bool(const jl_value* obj, const char* key, int* out, err_t* err) {
    const jl_value* v = jl_get(obj, key);
    if (!jl_is_bool(v)) return set_err(err, "field %s missing or not a boolean", key);
    *out = jl_bool(v);
    return 1;
}

static const char* get_str(const jl_value* obj, const char* key, err_t* err) {
    const char* s = jl_str(jl_get(obj, key));
    if (!s || !*s) set_err(err, "field %s missing or not a non-empty string", key);
    return s;
}

static const jl_value* get_obj(const jl_value* obj, const char* key, err_t* err) {
    const jl_value* v = jl_get(obj, key);
    if (!is_obj(v)) set_err(err, "field %s missing or not an object", key);
    return is_obj(v) ? v : NULL;
}

/* Exactly ROLL_COUNT integral numbers within [lo, hi]. */
static int read_rolls(const jl_value* arr, long lo, long hi, long out[ROLL_COUNT], err_t* err) {
    if (!jl_is_arr(arr)) return set_err(err, "rolls missing or not an array");
    if (jl_len(arr) != ROLL_COUNT) return set_err(err, "expected %d rolls, got %d", ROLL_COUNT, jl_len(arr));
    for (int i = 0; i < ROLL_COUNT; i++) {
        const jl_value* v = jl_at(arr, i);
        if (!jl_is_num(v)) return set_err(err, "roll %d is not a number", i);
        double d = jl_num(v);
        if (d != (double)(long)d) return set_err(err, "roll %d is not integral", i);
        if ((long)d < lo || (long)d > hi) return set_err(err, "roll %d out of range", i);
        out[i] = (long)d;
    }
    return 1;
}

/* ---------------------------------------------------------------- corpus validation */

static int validate_header(const jl_value* doc, err_t* err) {
    long version;
    if (!is_obj(doc)) return set_err(err, "corpus is not a JSON object");
    if (!get_int(doc, "schemaVersion", 0, 1000, &version, err)) return 0;
    if (version != ORACLE_SCHEMA_VERSION) return set_err(err, "unsupported corpus schemaVersion %ld", version);
    const jl_value* prov = get_obj(doc, "provenance", err);
    if (!prov) return 0;
    const jl_value* up = get_obj(prov, "hnsUpstream", err);
    if (!up) return 0;
    const char* commit = get_str(up, "commit", err);
    if (!commit) return 0;
    if (strcmp(commit, HNS_PINNED_COMMIT) != 0)
        return set_err(err, "corpus provenance commit %s is not the pinned H&S commit", commit);
    const jl_value* backend = get_obj(prov, "backend", err);
    if (!backend) return 0;
    const char* kind = get_str(backend, "kind", err);
    if (!kind) return 0;
    if (strcmp(kind, "pinned-expansion-battle-test-runner") != 0)
        return set_err(err, "unexpected oracle backend %s", kind);
    const jl_value* entries = jl_get(doc, "entries");
    if (!jl_is_arr(entries) || jl_len(entries) < 1) return set_err(err, "corpus has no entries");
    const char* previous = NULL;
    for (int i = 0; i < jl_len(entries); i++) {
        const jl_value* e = jl_at(entries, i);
        const jl_value* s = is_obj(e) ? jl_get(e, "scenario") : NULL;
        const char* id = s ? jl_str(jl_get(s, "id")) : NULL;
        if (!id) return set_err(err, "entry %d has no scenario id", i);
        if (previous && strcmp(previous, id) >= 0)
            return set_err(err, "scenario ids must be unique and sorted (%s after %s)", id, previous);
        long rolls[ROLL_COUNT];
        if (!read_rolls(jl_get(e, "rolls"), 0, 29999, rolls, err)) {
            char inner[512];
            snprintf(inner, sizeof(inner), "%s", err->message);
            return set_err(err, "%s: %s", id, inner);
        }
        previous = id;
    }
    return 1;
}

/* ---------------------------------------------------------------- request adapter */

static const char* capitalised_category(const char* c) {
    if (strcmp(c, "physical") == 0) return "Physical";
    if (strcmp(c, "special") == 0) return "Special";
    return NULL;
}

/* One battler of the production H&S request. `role` is "attacker" or "defender". */
static int emit_battler(sbuf* sb, const jl_value* scen_b, const jl_value* obs_b, const char* role, err_t* err) {
    long level, max_hp, hp_at_hit, atk, def, spa, spd, spe, atk_stage = 0, spa_stage = 0, def_stage = 0, spd_stage = 0;
    const jl_value* stats = get_obj(scen_b, "stats", err);
    const jl_value* stages = get_obj(scen_b, "stages", err);
    const jl_value* base = get_obj(obs_b, "baseStats", err);
    const jl_value* badges = get_obj(obs_b, "badgeBoosts", err);
    const jl_value* types = jl_get(obs_b, "types");
    const char* species = get_str(scen_b, "speciesLabel", err);
    const char* ability = get_str(scen_b, "abilityLabel", err);
    const char* status = get_str(scen_b, "status", err);
    const char* item_label = jl_str(jl_get(scen_b, "itemLabel"));
    if (!stats || !stages || !base || !badges || !species || !ability || !status) return 0;
    if (!jl_is_arr(types) || jl_len(types) < 1 || jl_len(types) > 2) return set_err(err, "%s types malformed", role);
    if (!get_int(scen_b, "level", 1, 100, &level, err) || !get_int(stats, "maxHp", 1, 65535, &max_hp, err) ||
        !get_int(obs_b, "hpAtHit", 1, 65535, &hp_at_hit, err) || !get_int(stats, "attack", 1, 65535, &atk, err) ||
        !get_int(stats, "defense", 1, 65535, &def, err) || !get_int(stats, "spAttack", 1, 65535, &spa, err) ||
        !get_int(stats, "spDefense", 1, 65535, &spd, err) || !get_int(stats, "speed", 1, 65535, &spe, err))
        return 0;
    if (strcmp(role, "attacker") == 0) {
        if (!get_int(stages, "attack", -6, 6, &atk_stage, err) || !get_int(stages, "spAttack", -6, 6, &spa_stage, err))
            return 0;
    } else {
        if (!get_int(stages, "defense", -6, 6, &def_stage, err) || !get_int(stages, "spDefense", -6, 6, &spd_stage, err))
            return 0;
    }
    long b_hp, b_atk, b_def, b_spa, b_spd, b_spe;
    if (!get_int(base, "hp", 1, 255, &b_hp, err) || !get_int(base, "attack", 1, 255, &b_atk, err) ||
        !get_int(base, "defense", 1, 255, &b_def, err) || !get_int(base, "spAttack", 1, 255, &b_spa, err) ||
        !get_int(base, "spDefense", 1, 255, &b_spd, err) || !get_int(base, "speed", 1, 255, &b_spe, err))
        return 0;
    int bb_atk, bb_def, bb_spa, bb_spd;
    if (!get_bool(badges, "attack", &bb_atk, err) || !get_bool(badges, "defense", &bb_def, err) ||
        !get_bool(badges, "spAttack", &bb_spa, err) || !get_bool(badges, "spDefense", &bb_spd, err))
        return 0;

    sb_append(sb, "\"%s\":{\"species\":", role);
    sb_json_string(sb, species);
    sb_append(sb, ",\"level\":%ld,\"ability\":", level);
    sb_json_string(sb, ability);
    if (item_label) {
        sb_append(sb, ",\"item\":");
        sb_json_string(sb, item_label);
    }
    if (strcmp(status, "burn") == 0) sb_append(sb, ",\"status\":\"brn\"");
    else if (strcmp(status, "poison") == 0) sb_append(sb, ",\"status\":\"psn\"");
    else if (strcmp(status, "none") != 0) return set_err(err, "%s status %s unsupported", role, status);
    sb_append(sb, ",\"overrides\":{\"types\":[");
    for (int i = 0; i < jl_len(types); i++) {
        const char* t = jl_str(jl_at(types, i));
        if (!t) return set_err(err, "%s type %d is not a string", role, i);
        if (i) sb_append(sb, ",");
        sb_json_string(sb, t);
    }
    sb_append(sb, "],\"baseStats\":{\"hp\":%ld,\"atk\":%ld,\"def\":%ld,\"spa\":%ld,\"spd\":%ld,\"spe\":%ld}}",
              b_hp, b_atk, b_def, b_spa, b_spd, b_spe);
    if (strcmp(role, "attacker") == 0) sb_append(sb, ",\"hp\":%ld,\"maxHP\":%ld", hp_at_hit, max_hp);
    sb_append(sb, ",\"rawStats\":{\"attack\":%ld,\"defense\":%ld,\"speed\":%ld,\"spAttack\":%ld,\"spDefense\":%ld}",
              atk, def, spe, spa, spd);
    /* gBattleMons statStages order: HP, Atk, Def, Speed, SpAtk, SpDef, Acc, Evasion (relative). */
    sb_append(sb, ",\"statStages\":[0,%ld,%ld,0,%ld,%ld,0,0]", atk_stage, def_stage, spa_stage, spd_stage);
    sb_append(sb, ",\"badgeBoosts\":{\"atk\":%s,\"def\":%s,\"spe\":false,\"spa\":%s,\"spd\":%s}}",
              bb_atk ? "true" : "false", bb_def ? "true" : "false", bb_spa ? "true" : "false",
              bb_spd ? "true" : "false");
    return 1;
}

/* Build the DualDex production H&S request for one corpus entry. */
static int build_request(const jl_value* entry, sbuf* sb, err_t* err) {
    const jl_value* scen = get_obj(entry, "scenario", err);
    const jl_value* obs = scen ? get_obj(entry, "observed", err) : NULL;
    if (!scen || !obs) return 0;
    const jl_value* s_atk = get_obj(scen, "attacker", err);
    const jl_value* s_def = get_obj(scen, "defender", err);
    const jl_value* o_atk = get_obj(obs, "attacker", err);
    const jl_value* o_def = get_obj(obs, "defender", err);
    const jl_value* o_move = get_obj(obs, "move", err);
    const jl_value* s_move = get_obj(scen, "move", err);
    const jl_value* rules = get_obj(scen, "rules", err);
    const jl_value* field = get_obj(scen, "field", err);
    const char* format = get_str(scen, "format", err);
    if (!s_atk || !s_def || !o_atk || !o_def || !o_move || !s_move || !rules || !field || !format) return 0;
    const char* move_label = get_str(s_move, "label", err);
    const char* move_type = get_str(o_move, "type", err);
    const char* category = get_str(o_move, "category", err);
    const char* style = get_str(rules, "optionStyle", err);
    const char* weather = get_str(field, "weather", err);
    long power = 0, target_count = 0;
    int crit = 0, reflect = 0, light_screen = 0;
    if (!move_label || !move_type || !category || !style || !weather) return 0;
    if (!get_int(o_move, "power", 1, 255, &power, err) || !get_int(obs, "targetCount", 1, 3, &target_count, err) ||
        !get_bool(scen, "crit", &crit, err) || !get_bool(field, "reflect", &reflect, err) ||
        !get_bool(field, "lightScreen", &light_screen, err))
        return 0;
    int doubles = strcmp(format, "doubles") == 0;
    if (!doubles && strcmp(format, "singles") != 0) return set_err(err, "unknown format %s", format);

    sb_append(sb, "{\"gen\":3,\"typeSystem\":\"hns_2_0_5\",");
    if (!emit_battler(sb, s_atk, o_atk, "attacker", err)) return 0;
    sb_append(sb, ",");
    if (!emit_battler(sb, s_def, o_def, "defender", err)) return 0;
    sb_append(sb, ",\"move\":{\"name\":");
    sb_json_string(sb, move_label);
    sb_append(sb, ",\"isCrit\":%s,\"overrides\":{\"basePower\":%ld,\"type\":", crit ? "true" : "false", power);
    sb_json_string(sb, move_type);
    /* CalcDataOverrides.buildHnsMoveOverride omits the category under the type-based option style
     * so the calculator derives it from the effective move type. */
    if (strcmp(style, "perMoveSplit") == 0) {
        const char* cap = capitalised_category(category);
        if (!cap) return set_err(err, "unknown move category %s", category);
        sb_append(sb, ",\"category\":\"%s\"", cap);
    } else if (strcmp(style, "typeBased") != 0) {
        return set_err(err, "unknown option style %s", style);
    }
    sb_append(sb, "}},\"field\":{\"gameType\":\"%s\"", doubles ? "Doubles" : "Singles");
    if (strcmp(weather, "rain") == 0) sb_append(sb, ",\"weather\":\"Rain\"");
    else if (strcmp(weather, "sun") == 0) sb_append(sb, ",\"weather\":\"Sun\"");
    else if (strcmp(weather, "none") != 0) return set_err(err, "unknown weather %s", weather);
    if (doubles) sb_append(sb, ",\"targetCount\":%ld", target_count);
    if (reflect || light_screen) {
        sb_append(sb, ",\"defenderSide\":{");
        if (reflect) sb_append(sb, "\"isReflect\":true");
        if (light_screen) sb_append(sb, "%s\"isLightScreen\":true", reflect ? "," : "");
        sb_append(sb, "}");
    }
    sb_append(sb, "}}");
    if (sb->oom) return set_err(err, "out of memory building the request");
    return 1;
}

/* ---------------------------------------------------------------- engine execution */

/* Validate a calculator response and extract its 16 rolls. Fails closed on anything else. */
static int parse_response_rolls(const char* response, long out[ROLL_COUNT], err_t* err) {
    if (!response) return set_err(err, "engine returned NULL");
    jl_value* doc = jl_parse(response);
    if (!doc) return set_err(err, "engine response is not valid JSON");
    int ok = 1;
    const jl_value* success = jl_get(doc, "success");
    if (!jl_is_bool(success) || !jl_bool(success)) {
        const char* msg = jl_str(jl_get(doc, "error"));
        ok = set_err(err, "engine refused the request: %s", msg ? msg : "(no error message)");
    } else if (!read_rolls(jl_get(doc, "damage"), 0, 1000000, out, err)) {
        ok = 0;
    }
    jl_free(doc);
    return ok;
}

static int run_request(const char* request, long out[ROLL_COUNT], err_t* err) {
    char* response = js_calc_calculate(request);
    int ok = parse_response_rolls(response, out, err);
    free(response);
    return ok;
}

/* -1 when equal, else the first differing roll index. */
static int first_difference(const long expected[ROLL_COUNT], const long actual[ROLL_COUNT]) {
    for (int i = 0; i < ROLL_COUNT; i++) {
        if (expected[i] != actual[i]) return i;
    }
    return -1;
}

static void print_rolls(const long r[ROLL_COUNT]) {
    printf("[");
    for (int i = 0; i < ROLL_COUNT; i++) printf("%s%ld", i ? "," : "", r[i]);
    printf("]");
}

/* ---------------------------------------------------------------- known divergences */

typedef struct {
    char* scenario;
    long calculator_rolls[ROLL_COUNT];
} known_divergence;

static known_divergence g_divergences[MAX_DIVERGENCES];
static int g_divergence_count = 0;
static int g_divergence_seen[MAX_DIVERGENCES];

static int load_divergences(const char* path, err_t* err) {
    char* text = read_file(path);
    if (!text) return set_err(err, "cannot read %s", path);
    jl_value* doc = jl_parse(text);
    free(text);
    if (!is_obj(doc)) { jl_free(doc); return set_err(err, "%s is not a JSON object", path); }
    long version;
    if (!get_int(doc, "schemaVersion", 0, 1000, &version, err)) { jl_free(doc); return 0; }
    if (version != 2) { jl_free(doc); return set_err(err, "unsupported divergence schemaVersion %ld", version); }
    const jl_value* list = jl_get(doc, "divergences");
    if (!jl_is_arr(list) || jl_len(list) > MAX_DIVERGENCES) { jl_free(doc); return set_err(err, "bad divergence list"); }
    for (int i = 0; i < jl_len(list); i++) {
        const jl_value* record = jl_at(list, i);
        const char* id = jl_str(jl_get(record, "scenario"));
        const char* issue = jl_str(jl_get(record, "issue"));
        if (!id || !issue) { jl_free(doc); return set_err(err, "divergence %d lacks scenario/issue", i); }
        for (int j = 0; j < g_divergence_count; j++) {
            if (strcmp(g_divergences[j].scenario, id) == 0) {
                jl_free(doc);
                return set_err(err, "duplicate known divergence %s", id);
            }
        }
        err_t rolls_err = {{0}};
        long calculator_rolls[ROLL_COUNT];
        if (!read_rolls(jl_get(record, "calculatorRolls"), 0, 29999, calculator_rolls, &rolls_err)) {
            jl_free(doc);
            return set_err(err, "divergence %s has invalid calculatorRolls: %s", id, rolls_err.message);
        }
        for (int j = 1; j < ROLL_COUNT; j++) {
            if (calculator_rolls[j] < calculator_rolls[j - 1]) {
                jl_free(doc);
                return set_err(err, "divergence %s calculatorRolls are not non-decreasing", id);
            }
        }
        g_divergences[g_divergence_count].scenario = strdup(id);
        memcpy(g_divergences[g_divergence_count].calculator_rolls, calculator_rolls, sizeof(calculator_rolls));
        g_divergence_count++;
    }
    jl_free(doc);
    return 1;
}

static int divergence_index(const char* id) {
    for (int i = 0; i < g_divergence_count; i++) {
        if (strcmp(g_divergences[i].scenario, id) == 0) return i;
    }
    return -1;
}

/* ---------------------------------------------------------------- the differential run */

typedef struct {
    int total, matched, diverged_registered, modelled, engine_only;
} run_stats;

/* Returns 1 when the scenario matched, 0 on mismatch, -1 on an error (always a failure). */
static int check_entry(const jl_value* entry, const long* override_expected, int report, int registered,
                       const long* pinned_calculator_rolls) {
    err_t err = {{0}};
    const jl_value* scen = jl_get(entry, "scenario");
    const char* id = jl_str(jl_get(scen, "id"));
    const char* surface = jl_str(jl_get(scen, "surface"));
    long expected[ROLL_COUNT], actual[ROLL_COUNT];
    if (!id || !surface) { if (report) fail("corpus entry without id/surface"); return -1; }
    if (override_expected) memcpy(expected, override_expected, sizeof(expected));
    else if (!read_rolls(jl_get(entry, "rolls"), 0, 29999, expected, &err)) {
        if (report) fail("%s: %s", id, err.message);
        return -1;
    }
    sbuf req = {0};
    if (!build_request(entry, &req, &err)) {
        if (report) fail("%s: cannot build request: %s", id, err.message);
        free(req.data);
        return -1;
    }
    if (!run_request(req.data, actual, &err)) {
        if (report) fail("%s: %s\n  request %s", id, err.message, req.data);
        free(req.data);
        return -1;
    }
    int diff = first_difference(expected, actual);
    int changed = registered && pinned_calculator_rolls
            ? first_difference(pinned_calculator_rolls, actual) : -1;
    if (diff >= 0 && report) {
        printf("HNS_ORACLE_MISMATCH {\"scenario\":\"%s\",\"surface\":\"%s\",\"registeredDivergence\":%s,"
               "\"firstDifferingRoll\":%d,\"expected\":",
               id, surface, registered ? "true" : "false", diff);
        print_rolls(expected);
        printf(",\"actual\":");
        print_rolls(actual);
        printf(",\"request\":%s}\n", req.data);
    }
    free(req.data);
    if (changed >= 0) {
        if (report) fail("%s: calculator mismatch changed from its pinned known-divergence vector at roll %d "
                         "(see HNS_ORACLE_MISMATCH)", id, changed);
        return -1;
    }
    return diff < 0 ? 1 : 0;
}

static void run_corpus(const jl_value* doc, run_stats* st) {
    const jl_value* entries = jl_get(doc, "entries");
    for (int i = 0; i < jl_len(entries); i++) {
        const jl_value* entry = jl_at(entries, i);
        const jl_value* scen = jl_get(entry, "scenario");
        const char* id = jl_str(jl_get(scen, "id"));
        const char* surface = jl_str(jl_get(scen, "surface"));
        st->total++;
        if (surface && strcmp(surface, "modelled") == 0) st->modelled++;
        else st->engine_only++;
        int reg = id ? divergence_index(id) : -1;
        const long* pinned = reg >= 0 ? g_divergences[reg].calculator_rolls : NULL;
        int result = check_entry(entry, NULL, 1, reg >= 0, pinned);
        if (result == 1) {
            st->matched++;
            if (reg >= 0) fail("%s is registered as a known divergence but now matches the oracle; "
                               "remove it from known_divergences.json (and close its issue if fixed)", id);
        } else if (result == 0) {
            if (reg >= 0) {
                st->diverged_registered++;
                g_divergence_seen[reg] = 1;
            } else {
                fail("%s: DualDex damage differs from the pinned H&S oracle (see HNS_ORACLE_MISMATCH)", id);
            }
        }
    }
    for (int i = 0; i < g_divergence_count; i++) {
        if (!g_divergence_seen[i] && divergence_index(g_divergences[i].scenario) == i) {
            int found = 0;
            for (int k = 0; k < jl_len(entries); k++) {
                const char* id = jl_str(jl_get(jl_get(jl_at(entries, k), "scenario"), "id"));
                if (id && strcmp(id, g_divergences[i].scenario) == 0) found = 1;
            }
            if (!found) fail("registered divergence %s is not a corpus scenario", g_divergences[i].scenario);
        }
    }
}

/* ---------------------------------------------------------------- self-tests */

static void self_tests(const jl_value* doc) {
    err_t err = {{0}};
    long a[ROLL_COUNT], b[ROLL_COUNT];
    for (int i = 0; i < ROLL_COUNT; i++) a[i] = b[i] = 40 + i;
    self_check("identical vectors match", first_difference(a, b) == -1);
    int every_index = 1;
    for (int k = 0; k < ROLL_COUNT; k++) {
        memcpy(b, a, sizeof(a));
        b[k] += 1;
        if (first_difference(a, b) != k) every_index = 0;
    }
    self_check("a single altered roll is detected at its exact index", every_index);

    /* Response validation. */
    self_check("a refused response is an error, not zero damage",
               !parse_response_rolls("{\"success\":false,\"error\":\"x\"}", a, &err));
    self_check("a 15-roll response is rejected",
               !parse_response_rolls("{\"success\":true,\"damage\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]}", a, &err));
    self_check("a fractional roll is rejected",
               !parse_response_rolls("{\"success\":true,\"damage\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16.5]}", a, &err));
    self_check("a string roll is rejected",
               !parse_response_rolls("{\"success\":true,\"damage\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,\"16\"]}", a, &err));
    self_check("a missing damage array is rejected", !parse_response_rolls("{\"success\":true}", a, &err));
    self_check("malformed JSON is rejected", !parse_response_rolls("{\"success\":true,", a, &err));
    self_check("a valid 16-roll response is accepted",
               parse_response_rolls("{\"success\":true,\"damage\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]}", a, &err) &&
               a[15] == 16);

    /* Corpus header / entry validation. */
    const char* base_head = "{\"schemaVersion\":1,\"provenance\":{\"hnsUpstream\":{\"commit\":\"" HNS_PINNED_COMMIT
                            "\"},\"backend\":{\"kind\":\"pinned-expansion-battle-test-runner\"}},\"entries\":[";
    const char* rolls16 = "[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]";
    const char* rolls15 = "[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]";
    char text[2048];
    snprintf(text, sizeof(text), "%s{\"scenario\":{\"id\":\"a\"},\"rolls\":%s},{\"scenario\":{\"id\":\"b\"},\"rolls\":%s}]}",
             base_head, rolls16, rolls16);
    jl_value* ok_doc = jl_parse(text);
    self_check("a well-formed minimal corpus header validates", validate_header(ok_doc, &err));
    jl_free(ok_doc);
    snprintf(text, sizeof(text), "%s{\"scenario\":{\"id\":\"a\"},\"rolls\":%s},{\"scenario\":{\"id\":\"a\"},\"rolls\":%s}]}",
             base_head, rolls16, rolls16);
    jl_value* dup = jl_parse(text);
    self_check("duplicate scenario ids are rejected", !validate_header(dup, &err));
    jl_free(dup);
    snprintf(text, sizeof(text), "%s{\"scenario\":{\"id\":\"a\"},\"rolls\":%s}]}", base_head, rolls15);
    jl_value* short_rolls = jl_parse(text);
    self_check("an entry with 15 rolls is rejected", !validate_header(short_rolls, &err));
    jl_free(short_rolls);
    jl_value* wrong_commit = jl_parse(
        "{\"schemaVersion\":1,\"provenance\":{\"hnsUpstream\":{\"commit\":\"0000000000000000000000000000000000000000\"},"
        "\"backend\":{\"kind\":\"pinned-expansion-battle-test-runner\"}},\"entries\":[{\"scenario\":{\"id\":\"a\"},"
        "\"rolls\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}]}");
    self_check("a corpus from another H&S commit is rejected", !validate_header(wrong_commit, &err));
    jl_free(wrong_commit);
    jl_value* wrong_backend = jl_parse(
        "{\"schemaVersion\":1,\"provenance\":{\"hnsUpstream\":{\"commit\":\"" HNS_PINNED_COMMIT "\"},"
        "\"backend\":{\"kind\":\"smogon-calc\"}},\"entries\":[{\"scenario\":{\"id\":\"a\"},"
        "\"rolls\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}]}");
    self_check("a corpus from a non-oracle backend is rejected", !validate_header(wrong_backend, &err));
    jl_free(wrong_backend);

    /* End to end: the first matching real entry must match, and altering any one of its expected
     * rolls must be caught by the same path the corpus run uses. */
    const jl_value* entries = jl_get(doc, "entries");
    const jl_value* probe = NULL;
    for (int i = 0; i < jl_len(entries) && !probe; i++) {
        const jl_value* e = jl_at(entries, i);
        const char* id = jl_str(jl_get(jl_get(e, "scenario"), "id"));
        if (id && divergence_index(id) < 0 && check_entry(e, NULL, 0, 0, NULL) == 1) probe = e;
    }
    self_check("some corpus entry matches exactly", probe != NULL);
    if (probe) {
        long expected[ROLL_COUNT];
        read_rolls(jl_get(probe, "rolls"), 0, 29999, expected, &err);
        int caught = 1;
        for (int k = 0; k < ROLL_COUNT; k++) {
            long altered[ROLL_COUNT];
            memcpy(altered, expected, sizeof(altered));
            altered[k] += 1;
            if (check_entry(probe, altered, 0, 0, NULL) != 0) caught = 0;
        }
        self_check("the differential catches one altered expected roll at every index", caught);
        self_check("the unaltered expected vector still matches", check_entry(probe, expected, 0, 0, NULL) == 1);
    }
}

int main(int argc, char** argv) {
    const char* corpus_path = argc > 1 ? argv[1] : "tools/hns-damage-oracle/corpus.json";
    const char* divergence_path = argc > 2 ? argv[2] : "tools/hns-damage-oracle/known_divergences.json";
    const char* bundle_path = "app/src/main/assets/calc_bundle.js";
    err_t err = {{0}};

    printf("== H&S differential damage oracle (pinned %s) ==\n", HNS_PINNED_COMMIT);
    char* bundle = read_file(bundle_path);
    if (!bundle || !js_calc_init(bundle)) {
        fprintf(stderr, "FAIL: cannot load the shipped calculator bundle %s\n", bundle_path);
        return 1;
    }
    free(bundle);
    char* text = read_file(corpus_path);
    if (!text) {
        fprintf(stderr, "FAIL: cannot read the oracle corpus %s\n", corpus_path);
        return 1;
    }
    jl_value* doc = jl_parse(text);
    free(text);
    if (!doc || !validate_header(doc, &err)) {
        fprintf(stderr, "FAIL: invalid oracle corpus: %s\n", doc ? err.message : "not valid JSON");
        return 1;
    }
    if (!load_divergences(divergence_path, &err)) {
        fprintf(stderr, "FAIL: %s\n", err.message);
        return 1;
    }

    run_stats st = {0};
    run_corpus(doc, &st);
    self_tests(doc);

    printf("scenarios: %d (%d modelled, %d engine-only); exact 16-roll matches: %d; registered divergences: %d/%d; "
           "self-checks: %d\n",
           st.total, st.modelled, st.engine_only, st.matched, st.diverged_registered, g_divergence_count,
           g_self_checks);
    jl_free(doc);
    for (int i = 0; i < g_divergence_count; i++) free(g_divergences[i].scenario);
    js_calc_cleanup();
    if (g_failures) {
        printf("H&S differential damage oracle: %d failure(s)\n", g_failures);
        return 1;
    }
    printf("H&S differential damage oracle: PASS\n");
    return 0;
}
