#!/usr/bin/env python3
"""Generate base-species and CanEvolve authority from the pinned H&S build."""
import argparse
import json
import re
import sys
from pathlib import Path

PIN = "1f42b74dff0e9fe942419845d040663dd829a973"
ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "app/src/main/java/com/dualdex/pokemon/hns/Hns205SpeciesMechanics.kt"
sys.path.insert(0, str(ROOT / "tools/hns-data-pack"))
import generate_hns_data_pack as data_pack  # noqa: E402


def fail(message):
    raise ValueError(message)


def parse_species_constants(upstream):
    constants = {}
    for line in (upstream / "include/constants/species.h").read_text().splitlines():
        m = re.match(r"\s*#define\s+(SPECIES_[A-Z0-9_]+)\s+(\d+)\s*$", line)
        if m:
            constants[m.group(1)] = int(m.group(2))
    if not constants or constants.get("SPECIES_NONE") != 0:
        fail("could not parse pinned species ID constants")
    maximum = max(value for symbol, value in constants.items() if symbol != "SPECIES_SHINY_TAG")
    return constants, maximum + 1


def extract_array_entries(output, start, key_pattern, label):
    return data_pack.extract_designated_entries(output, start, key_pattern, label)


def build_data(upstream, cpp):
    constants, species_count = parse_species_constants(upstream)
    output = data_pack.run_cpp(cpp, str(upstream), "src/pokemon.c")
    species_start = output.find("gSpeciesInfo[] =")
    if species_start < 0:
        fail("preprocessed src/pokemon.c has no gSpeciesInfo table")
    species_entries = extract_array_entries(output, species_start, r"\d+", "gSpeciesInfo")
    form_tables = {}
    for match in re.finditer(
        r"static\s+const\s+u16\s+(s[A-Za-z0-9_]+FormSpeciesIdTable)\[\]\s*=\s*\{([^}]*)\}",
        output,
        re.S,
    ):
        values = [int(value) for value in re.findall(r"(?<![A-Za-z_])\d+(?![A-Za-z_])", match.group(2))]
        if values:
            form_tables[match.group(1)] = values[0]

    base_species = {}
    can_evolve = set()
    for species_id_raw, body in species_entries:
        species_id = int(species_id_raw)
        if not 0 <= species_id < species_count:
            fail(f"gSpeciesInfo species ID out of domain: {species_id}")
        form_match = re.search(r"\.formSpeciesIdTable\s*=\s*(s[A-Za-z0-9_]+FormSpeciesIdTable)", body)
        if form_match:
            table = form_match.group(1)
            if table not in form_tables:
                fail(f"missing compiled form species table {table}")
            base_species[species_id] = form_tables[table]
        else:
            base_species[species_id] = species_id

        for method, target in re.findall(
            r"\{\s*(EVO_[A-Z0-9_]+)\s*,[^{}]*?,\s*(\d+)\s*\}", body
        ):
            if method != "EVO_NONE" and int(target) != 0:
                if int(target) >= species_count:
                    fail(f"evolution target outside species domain: {target}")
                can_evolve.add(species_id)
                break

    if len(base_species) < 1000:
        fail(f"gSpeciesInfo unexpectedly has only {len(base_species)} rows")
    return species_count, base_species, can_evolve


def render(species_count, base_species, can_evolve):
    overrides = {k: v for k, v in base_species.items() if k != v}
    lines = [
        "// Generated by tools/hns-items/generate_hns_species_mechanics.py; do not edit.",
        f"// Pinned source: {PIN}",
        "package com.dualdex.pokemon.hns",
        "",
        "/** Exact GET_BASE_SPECIES_ID / CanEvolve operands from the pinned H&S source tables. */",
        "internal object Hns205SpeciesMechanics {",
        f"    const val SPECIES_COUNT = {species_count}",
        "    private val baseSpeciesOverrides: Map<Int, Int> = mapOf(",
    ]
    for species_id, base_id in sorted(overrides.items()):
        lines.append(f"        {species_id} to {base_id},")
    lines += [
        "    )",
        "    private val knownSpecies: Set<Int> = setOf(",
    ]
    for species_id in sorted(base_species):
        lines.append(f"        {species_id},")
    lines += [
        "    )",
        "    private val canEvolveSpecies: Set<Int> = setOf(",
    ]
    for species_id in sorted(can_evolve):
        lines.append(f"        {species_id},")
    lines += [
        "    )",
        "    fun baseSpeciesId(speciesId: Int?): Int? = speciesId?.takeIf { it in 0 until SPECIES_COUNT && it in knownSpecies }",
        "        ?.let { baseSpeciesOverrides[it] ?: it }",
        "    fun canEvolve(speciesId: Int?): Boolean? = speciesId?.takeIf { it in knownSpecies }?.let { it in canEvolveSpecies }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-dir", required=True)
    parser.add_argument("--cpp-bin", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    upstream = Path(args.upstream_dir)
    data_pack.verify_git_commit(str(upstream))
    species_count, base_species, can_evolve = build_data(upstream, args.cpp_bin)
    output = render(species_count, base_species, can_evolve)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            fail(f"generated species authority is stale: {OUTPUT}")
    else:
        OUTPUT.write_text(output)
    print(f"species authority: {species_count} IDs, {len(base_species)} base mappings, {len(can_evolve)} evolvable")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
